services:
  laravel:
    build:
      context: .
    ports:
      - "${SERVER_PORT:-9000}:${SERVER_PORT:-9000}"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-laravel_db}
      DB_USERNAME: root
      DB_PASSWORD: ${ROOT_PASSWORD:-123123}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${ROOT_PASSWORD:-123123}" ]
      timeout: 20s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-123123}
      MYSQL_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME:-laravel_db}
    volumes:
      - laravel_volume:/var/lib/mysql

volumes:
  laravel_volume: